# Generated by Django 2.2.3 on 2019-09-29 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import homesapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_phone', models.CharField(max_length=15)),
                ('agent_desc', models.TextField()),
                ('member_since', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('agent_image', models.ImageField(default='default.jpg', upload_to='agent_pics')),
                ('IsActive', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_desc', models.TextField(blank=True)),
                ('prop_address1', models.CharField(blank=True, max_length=200)),
                ('prop_address2', models.CharField(blank=True, max_length=200)),
                ('prop_city', models.CharField(blank=True, max_length=100)),
                ('prop_state', models.CharField(blank=True, max_length=3)),
                ('prop_zip', models.CharField(max_length=10)),
                ('area', models.FloatField(null=True)),
                ('year_built', models.SmallIntegerField(default=1900)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('price_type', django_enumfield.db.fields.EnumField(default=0, enum=homesapp.models.PriceType)),
                ('no_of_beds', models.IntegerField(default=0)),
                ('no_of_baths', models.IntegerField(default=0)),
                ('floor_type', models.CharField(max_length=200)),
                ('IsShared', models.BooleanField(default=False)),
                ('IsRental', models.BooleanField(default=False)),
                ('rent_term', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homesapp.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('agency_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('agency_phone', models.CharField(max_length=15)),
                ('agency_address1', models.CharField(max_length=200)),
                ('agency_address2', models.CharField(max_length=200)),
                ('agency_city', models.CharField(max_length=100)),
                ('agency_state', models.CharField(max_length=3)),
                ('agency_zip', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('img_desc', models.CharField(default='image', max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homesapp.Property')),
            ],
        ),
    ]
