# Generated by Django 2.2.3 on 2019-09-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0002_auto_20190929_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_desc',
            field=models.TextField(null=True),
        ),
    ]
