# Generated by Django 2.2.3 on 2019-09-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0003_auto_20190929_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(default='property.jpg', upload_to='property_pics'),
        ),
    ]
