# Generated by Django 2.2.3 on 2019-09-30 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homesapp', '0005_auto_20190929_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='user_id',
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_address1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_state',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='agency_address2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
