# Generated by Django 2.2.3 on 2019-10-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0006_auto_20190930_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_type',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
