# Generated by Django 2.2.3 on 2019-10-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0007_auto_20191021_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorite',
        ),
    ]
