# Generated by Django 2.2.3 on 2019-11-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0008_remove_property_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_image',
            field=models.ImageField(default='property.jpg', upload_to='cover_pics'),
        ),
    ]
