# Generated by Django 2.2.3 on 2019-11-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0009_property_prop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
