# Generated by Django 2.2.3 on 2019-12-03 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0010_auto_20191125_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
