# Generated by Django 2.2.3 on 2019-12-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0011_agent_agent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_email',
        ),
    ]
