# Generated by Django 2.2.3 on 2019-12-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0012_remove_agent_agent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='agent_pics'),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_image',
            field=models.ImageField(blank=True, default='property.jpg', upload_to='cover_pics'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(blank=True, default='property.jpg', upload_to='property_pics'),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='img_desc',
            field=models.CharField(blank=True, default='image', max_length=200),
        ),
    ]
