# Generated by Django 2.2.3 on 2019-12-18 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0014_auto_20191209_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price_type',
        ),
    ]
