# Generated by Django 2.2.3 on 2019-12-19 01:46

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0015_remove_property_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagency',
            name='agency_phone',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
