# Generated by Django 2.2.3 on 2019-09-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
