# Generated by Django 2.2.3 on 2019-10-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0008_remove_property_favorite'),
        ('users', '0003_auto_20190929_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to='homesapp.Property'),
        ),
    ]
